import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ArrowRight, BarChart3, Bot, Building2, CalendarClock, Check, CircleDollarSign, ClipboardCheck, FileSpreadsheet, FolderLock, HandCoins, House, KeyRound, Landmark, MessageCircle, ShieldCheck, Sparkles, Upload, UserRound, Users, WalletCards, Wrench } from "lucide-react";
import { BrandLogo } from "@/components/BrandLogo";
import { LandingAnalytics } from "@/components/LandingAnalytics";
import { ProductShowcase } from "@/components/ProductShowcase";
import { AiMarketingDemo } from "@/components/AiMarketingDemo";
import { MobileLandingNav } from "@/components/MobileLandingNav";
import { BRAND_NAME, BRAND_SIGNATURE, BRAND_TITLE, COMPANY_NINEA, COMPANY_RCCM } from "@/lib/brand";

export const metadata: Metadata = {
  title: BRAND_TITLE,
  description: "Logiciel de gestion locative au Sénégal pour centraliser biens, loyers, propriétaires, locataires, paiements, CRM et opérations avec une intelligence métier sécurisée.",
  keywords: ["logiciel gestion immobilière Sénégal", "gestion locative Sénégal", "logiciel agence immobilière", "gestion propriétaires", "gestion biens immobiliers", "logiciel loyers", "CRM immobilier Sénégal", "IA immobilier"],
  robots: { index: true, follow: true },
};

const modules = [
  [Building2, "Biens & immeubles", "Structurez votre patrimoine, ses unités et ses documents."], [UserRound, "Propriétaires", "Consolidez encaissements, dépenses et reversements."],
  [Users, "Locataires & contrats", "Suivez occupants, baux, échéances et renouvellements."], [WalletCards, "Paiements & impayés", "Visualisez attendu, encaissé, soldes et relances."],
  [Sparkles, "CRM prospects", "Qualifiez les demandes et rapprochez-les des bons biens."], [Wrench, "Maintenance", "Priorisez tickets, prestataires, coûts et délais."],
  [FolderLock, "Documents & rapports", "Gardez pièces privées, exports et rapports au même endroit."], [Bot, "Intelligence AI", "Interrogez vos données métier et obtenez des actions claires."],
] as const;

const profiles = [
  ["Agence immobilière", ["Centraliser biens et mandats", "Transformer prospects en visites", "Suivre commissions et transactions"]],
  ["Gestionnaire locatif", ["Encaisser et suivre les loyers", "Traiter les impayés", "Préparer les reversements propriétaires"]],
  ["Propriétaire / SCI", ["Suivre son patrimoine", "Mesurer revenus et dépenses", "Contrôler occupation et rentabilité"]],
  ["Investisseur", ["Comparer les performances", "Identifier les actifs sous-performants", "Suivre rendement et vacance"]],
  ["Entreprise", ["Centraliser le patrimoine", "Organiser les accès", "Consolider les rapports"]],
  ["Promoteur", ["Programmes immobiliers", "Unités et réservations", "Échéanciers"], "Bientôt"],
] as const;
const faq = [
  ["Puis-je importer mes fichiers Excel ?", "Oui. L’assistant accepte CSV et XLSX avec aperçu, correspondance des colonnes, validation et rapport."],
  ["Puis-je gérer plusieurs propriétaires ?", "Oui. Chaque propriétaire dispose de ses biens, encaissements, dépenses et montants à reverser."],
  ["Peut-on suivre les impayés ?", "Oui. Les soldes, retards et priorités de relance sont visibles et filtrables."],
  ["Puis-je utiliser Wave et Orange Money ?", "Oui pour enregistrer et suivre ces modes de règlement. Les connexions API dépendent de votre configuration."],
  ["Intelligence Immobilier encaisse-t-il mon argent ?", "Non. La version actuelle enregistre et suit vos règlements ; elle ne se présente pas comme dépositaire des fonds."],
  ["L’IA peut-elle modifier mes données ?", "Les actions sensibles restent soumises aux droits et à une validation explicite."],
  ["Mes collaborateurs peuvent-ils avoir des permissions différentes ?", "Oui. Les rôles et permissions séparent les capacités de consultation, de gestion, de finance et d’administration."],
  ["Puis-je utiliser Intelligence Immobilier sur téléphone et tablette ?", "Oui. Le site et l’application s’adaptent aux écrans mobiles et tablettes."],
  ["Mes documents sont-ils privés ?", "L’accès est isolé par organisation et contrôlé par rôle. Le niveau de stockage privé dépend du fournisseur configuré."],
  ["Existe-t-il une version pour les promoteurs ?", "Un module promoteur dédié est prévu, mais il n’est pas encore présenté comme opérationnel."],
] as const;

export default function LandingPage() {
  return <main className="ii-landing"><LandingAnalytics/>
    <section className="ii-hero-shell">
      <header className="ii-landing-nav"><Link href="/" aria-label={`${BRAND_NAME} — Accueil`}><BrandLogo variant="wordmark" light priority/></Link><nav aria-label="Navigation du site"><a href="#produit">Produit</a><a href="#intelligence">Intelligence AI</a><a href="#solutions">Solutions</a><a href="#tarifs">Tarifs</a></nav><div><Link href="/login" className="ii-nav-login">Se connecter</Link><Link href="/register" className="ii-button compact" data-analytics="hero_start_trial">Commencer gratuitement</Link></div><MobileLandingNav/></header>
      <div className="ii-hero"><div className="ii-hero-copy"><p className="ii-kicker ii-official-signature"><Sparkles size={14}/>{BRAND_SIGNATURE}</p><h1>Gérez votre immobilier.<br/><em>L’intelligence fait le reste.</em></h1><p>Gérez vos biens, loyers, propriétaires, locataires, paiements, prospects et opérations depuis une seule plateforme intelligente.</p><p className="ii-hero-audience">Pour les agences, gestionnaires, propriétaires, promoteurs, SCI et équipes immobilières.</p><div className="ii-hero-actions"><Link href="/register" className="ii-button" data-analytics="hero_start_trial">Commencer gratuitement <ArrowRight size={16}/></Link><Link href="/demo" className="ii-button ghost" data-analytics="hero_demo">Explorer la démo</Link></div><a className="ii-explore-link" href="#produit">Explorer la plateforme <ArrowRight size={13}/></a><span><ShieldCheck size={14}/>Aucune carte requise · Données isolées par organisation</span></div>
        <div className="ii-hero-visual" aria-label="Aperçu produit avec données fictives"><div className="ii-brand-halo"/><BrandLogo variant="full" className="ii-official-hero-logo" priority/><div className="ii-demo-label">APERÇU PRODUIT · DONNÉES FICTIVES</div><div className="ii-dashboard-preview"><header><span/><span/><span/><b>TABLEAU DE BORD</b></header><aside><i/><i/><i/><i/><i/></aside><section><div className="ii-preview-heading"><span>Bonjour Mamadou</span><small>Situation du portefeuille de démonstration</small></div><div className="ii-preview-kpis"><i/><i/><i/><i/></div><div className="ii-preview-chart"><b>15,92 M FCFA encaissés</b><div>{[46,61,57,74,69,88,80,95].map(h=><i key={h} style={{height:`${h}%`}}/>)}</div></div></section></div><div className="ii-floating-metric metric-one"><i><BarChart3 size={16}/></i><span><small>Occupation</small><b>91,4 %</b></span></div><div className="ii-floating-metric metric-two"><i><AlertTriangle size={16}/></i><span><small>Impayés</small><b>2,53 M FCFA</b></span></div></div>
      </div><div className="ii-trust-strip"><span>Gestion locative</span><i/><span>CRM immobilier</span><i/><span>Recouvrement</span><i/><span>Intelligence métier contrôlée</span></div>
    </section>
    <section className="ii-capabilities" aria-label="Fonctionnalités principales">{[[House,"Biens & unités"],[KeyRound,"Contrats & locataires"],[CircleDollarSign,"Finance & recouvrement"],[Wrench,"Maintenance"],[FileSpreadsheet,"Rapports & imports"],[Bot,"Assistant IA"]].map(([Icon,label])=>{const I=Icon as typeof House;return <span key={String(label)}><I size={16}/>{String(label)}</span>})}</section>

    <section className="ii-solution ii-modules-section" id="plateforme"><div className="ii-section-heading"><p className="ii-kicker">TOUT VOTRE IMMOBILIER EN UN SEUL ENDROIT</p><h2>Une plateforme complète.<br/><em>Une activité plus lisible.</em></h2><p>Chaque module partage la même donnée pour limiter les doubles saisies et rendre les prochaines actions visibles.</p></div><div className="ii-module-grid">{modules.map(([Icon,title,text])=><article key={title}><i><Icon size={21}/></i><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <ProductShowcase/>

    <section className="ii-today-section"><div><p className="ii-kicker">INTELLIGENCE OPÉRATIONNELLE</p><h2>Commencez chaque journée par ce qui compte.</h2><p>Intelligence Immobilier centralise vos priorités pour que rien ne passe entre les mailles du filet.</p></div><div className="ii-today-list">{[[CircleDollarSign,"12","Loyers à relancer","Voir","/arrears"],[CalendarClock,"5","Contrats à renouveler","Examiner","/contracts"],[Wrench,"3","Tickets urgents","Traiter","/maintenance"],[Users,"7","Prospects à rappeler","Rappeler","/leads"],[HandCoins,"2","Reversements","Valider","/owner-statements"]].map(([Icon,value,label,action,href])=>{const I=Icon as typeof House;return <article key={String(label)}><i><I size={17}/></i><strong>{String(value)}</strong><span><b>{String(label)}</b><small>Données de démonstration</small></span><Link href={String(href)}>{String(action)}<ArrowRight size={13}/></Link></article>})}</div></section>

    <AiMarketingDemo/>

    <section className="ii-owner-section" id="proprietaires"><div className="ii-owner-dashboard"><header><Landmark size={19}/><span><b>Amadou Fall</b><small>Espace propriétaire · 12 biens</small></span><em>DONNÉES DE DÉMONSTRATION</em></header><div className="ii-owner-kpis"><span><small>Mes biens</small><b>12</b></span><span><small>Occupation</small><b>92 %</b></span><span><small>Loyers encaissés</small><b>3 850 000 <em>FCFA</em></b></span><span><small>Dépenses</small><b>225 000 <em>FCFA</em></b></span><span className="featured"><small>Net à reverser</small><b>3 240 000 <em>FCFA</em></b></span></div><div className="ii-owner-activity"><section><h3>Paiements récents</h3>{[["Villa Ndar","850 000","Aujourd’hui"],["Horizon Mermoz","575 000","Hier"],["Studio Point E","325 000","29 août"]].map(([property,amount,date])=><div key={property}><i><Check size={12}/></i><span><b>{property}</b><small>{date}</small></span><strong>{amount} FCFA</strong></div>)}</section><aside><span><Wrench size={15}/><b>2 travaux</b><small>dont 1 à valider</small></span><span><FolderLock size={15}/><b>18 documents</b><small>relevés et justificatifs</small></span><span><FileSpreadsheet size={15}/><b>Historique</b><small>12 mois consolidés</small></span></aside></div></div><div><p className="ii-kicker">ESPACE PROPRIÉTAIRE</p><h2>Moins d’appels.<br/>Plus de transparence.</h2><p>Donnez à chaque propriétaire une vision claire de ses biens, encaissements, dépenses, travaux et reversements.</p><Link href="/demo" className="ii-button" data-analytics="hero_demo">Explorer la démo <ArrowRight size={16}/></Link></div></section>

    <section className="ii-operations-grid"><article><i><WalletCards size={23}/></i><p className="ii-kicker">PAIEMENTS & RECOUVREMENT</p><h2>Suivez vos encaissements sans perdre le contrôle.</h2><div className="ii-finance-kpis">{[["Loyers attendus","18 450 000"],["Encaissés","15 920 000"],["Impayés","2 530 000"],["Taux de recouvrement","86,3 %"]].map(([label,value])=><span key={label}><small>{label}</small><b>{value}{label!=="Taux de recouvrement"&&" FCFA"}</b></span>)}</div><ul>{["Espèces","Wave","Orange Money","Virement","Chèque"].map(x=><li key={x}>{x}</li>)}</ul><small>Données de démonstration. La plateforme suit les règlements ; elle n’encaisse pas directement les fonds.</small></article><article className="ii-whatsapp-card"><i><MessageCircle size={23}/></i><p className="ii-kicker">COMMUNICATION CLIENT</p><h2>Vos communications immobilières, sans friction.</h2><div className="ii-whatsapp-flow"><span><i><FileSpreadsheet size={16}/></i><b>Quittance créée</b></span><ArrowRight size={16}/><span><i><ArrowRight size={16}/></i><b>Partager</b></span><ArrowRight size={16}/><span><i><MessageCircle size={16}/></i><b>WhatsApp</b></span></div><blockquote>« Bonjour, votre quittance d’août est disponible. »</blockquote><small>Intégration WhatsApp Business selon configuration. Aucun envoi automatique n’est revendiqué.</small></article></section>

    <section className="ii-crm-section" id="crm"><div className="ii-crm-copy"><p className="ii-kicker">CRM IMMOBILIER</p><h2>Du premier contact<br/><em>à la signature.</em></h2><p>Faites avancer chaque prospect et gardez la prochaine action visible à chaque étape.</p><Link href="/demo" className="ii-button" data-analytics="hero_demo">Explorer le CRM <ArrowRight size={15}/></Link></div><div className="ii-crm-kanban"><header><span>Pipeline commercial</span><em>DONNÉES DE DÉMONSTRATION</em></header><div>{[["Nouveau",[["Moussa Diop","Villa","450–600k"]]],["Contacté",[["Aminata Sarr","Bureau","900k–1,2M"]]],["Qualifié",[["Awa Fall","Appartement F4","600–800k"]]],["Visite",[["Cheikh Ba","Appartement F3","500–650k"]]],["Négociation",[["SCI Horizon","Plateau","1,4–1,8M"]]],["Gagné",[["Fatou Ndiaye","Studio","325k"]]]].map(([stage,cards],index)=><section key={String(stage)}><h3><i>{index+1}</i>{String(stage)}</h3>{(cards as string[][]).map(([name,need,budget])=><article key={name}><b>{name}</b><span>{need}</span><small>{budget} FCFA</small>{name==="Awa Fall"&&<em>92 % compatible</em>}</article>)}</section>)}</div></div></section>

    <section className="ii-import-section"><div><p className="ii-kicker">IMPORT EXCEL / CSV</p><h2>Vous utilisez déjà Excel ?<br/><em>Importez votre portefeuille.</em></h2><p>Biens, propriétaires, locataires, contrats et loyers suivent un parcours contrôlé.</p><Link href="/register" className="ii-button" data-analytics="excel_import_cta">Importer mes données <Upload size={15}/></Link></div><div className="ii-import-visual"><header><FileSpreadsheet size={19}/><span><b>gestion.xlsx</b><small>Illustration produit · données fictives</small></span><Check size={16}/></header><div className="ii-import-detection"><p>Détection</p>{["Biens","Propriétaires","Locataires","Contrats"].map(item=><span key={item}><Check size={12}/>{item}</span>)}</div><div className="ii-import-validation"><span><ClipboardCheck size={18}/><b>486</b><small>lignes valides</small></span><span><AlertTriangle size={18}/><b>9</b><small>anomalies à vérifier</small></span></div><footer><span>Fichier</span><i/><span>Détection</span><i/><span>Vérification</span><i/><b>Importer</b></footer></div></section>

    <section className="ii-profiles" id="solutions"><div className="ii-section-heading"><p className="ii-kicker">CAS D’USAGE</p><h2>Conçu pour les professionnels<br/><em>de l’immobilier.</em></h2><p>Chaque métier retrouve ses priorités, ses indicateurs et ses actions.</p></div><div className="ii-profile-grid">{profiles.map(([title,benefits,badge],index)=><article key={title}>{badge&&<em>{badge}</em>}<span className="ii-profile-number">0{index+1}</span><h3>{title}</h3><ul>{benefits.map(benefit=><li key={benefit}><Check size={13}/>{benefit}</li>)}</ul></article>)}</div></section>

    <section className="ii-security" id="securite"><div><p className="ii-kicker">SÉCURITÉ & CONFIANCE</p><h2>Vos données immobilières méritent une sécurité professionnelle.</h2><p>Les affirmations ci-contre correspondent aux contrôles présents dans l’application ; le stockage documentaire dépend du fournisseur configuré.</p><nav><Link href="/securite">Voir la sécurité</Link><Link href="/confidentialite">Confidentialité</Link></nav></div><div className="ii-security-list">{[["Isolation par organisation","Les requêtes métier sont filtrées sur l’organisation active."],["Rôles et permissions","Les capacités diffèrent selon le rôle attribué."],["Permissions serveur","Les mutations protégées vérifient le contexte et le droit requis."],["Journal d’audit","Les créations critiques enregistrent acteur, action et organisation."],["Sessions sécurisées","Jetons de session limités dans le temps et cookies sécurisés en production."],["En-têtes de protection","Protection contre l’intégration en iframe, sniffing et référents excessifs."]].map(([title,text])=><span key={title}><i><Check/></i><b>{title}</b><small>{text}</small></span>)}</div></section>

    <section className="ii-pricing" id="tarifs"><div className="ii-section-heading"><p className="ii-kicker">DES PLANS ADAPTÉS À VOTRE CROISSANCE</p><h2>Commencez simplement.</h2><p>Choisissez le niveau d’accompagnement adapté à votre organisation.</p></div><div className="ii-pricing-grid">{[["SOLO","19 900",["Gestion locative","Paiements & impayés","Imports & rapports"]],["AGENCE","49 900",["Gestion locative & CRM","Maintenance & rapports","Intelligence AI"]],["ENTREPRISE","Sur mesure",["Rôles & audit","Intégrations selon configuration","Accompagnement dédié"]]].map(([plan,price,items],i)=><article className={i===1?"featured":""} key={String(plan)}>{i===1?<em>RECOMMANDÉ POUR LES AGENCES</em>:null}<p>{String(plan)}</p><h3>{String(price)} {i<2?<small>FCFA / mois</small>:null}</h3><span>{i===0?"Pour le gestionnaire indépendant.":i===1?"Pour une équipe immobilière structurée.":"Pour les grands portefeuilles."}</span><ul>{(items as string[]).map(x=><li key={x}><Check/>{x}</li>)}</ul>{i<2?<Link href="/register" data-analytics="pricing_select" data-analytics-label={String(plan)}>Choisir {String(plan).toLowerCase()}</Link>:<a href="mailto:contact@intelligenceimmobilier.com" data-analytics="pricing_select" data-analytics-label="ENTREPRISE">Nous contacter</a>}</article>)}</div>
      <div className="ii-pricing-comparison" aria-label="Comparatif des offres"><div className="ii-comparison-row head"><b>Fonctionnalité</b><b>Solo</b><b>Agence</b><b>Entreprise</b></div>{[["Biens, propriétaires, locataires et contrats","✓","✓","✓"],["Paiements, quittances et impayés","✓","✓","✓"],["CRM et visites","—","✓","✓"],["Maintenance et documents","—","✓","✓"],["Rapports et imports","✓","✓","✓"],["Intelligence AI","—","✓","✓"],["Rôles avancés et audit","—","—","✓"],["Support","Standard","Prioritaire","Dédié"],["API et intégrations","—","Selon configuration","Selon configuration"]].map(row=><div className="ii-comparison-row" key={row[0]}>{row.map((cell,index)=>index===0?<b key={cell}>{cell}</b>:<span key={`${row[0]}-${cell}-${index}`}>{cell}</span>)}</div>)}</div>
      <p className="ii-pricing-note">Aucun quota backend non vérifié n’est affiché. Les périmètres commerciaux et intégrations sont confirmés avant souscription.</p></section>

    <section className="ii-pilot-section"><p className="ii-kicker">EN PHASE DE LANCEMENT</p><h2>Programme pilote disponible.</h2><p>Découvrez Intelligence Immobilier avec vos propres cas d’usage.</p><div><Link className="ii-button" href="/demo" data-analytics="hero_demo">Explorer la démo</Link><Link className="ii-button ghost" href="/register" data-analytics="hero_start_trial">Commencer gratuitement</Link></div></section>

    <section className="ii-faq" id="faq"><div className="ii-section-heading"><p className="ii-kicker">QUESTIONS FRÉQUENTES</p><h2>Des réponses claires<br/><em>avant de commencer.</em></h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>

    <section className="ii-final-cta"><BrandLogo variant="symbol" light/><p className="ii-kicker">PRÊT À PILOTER AUTREMENT ?</p><h2>Votre gestion immobilière mérite mieux qu’un tableur.</h2><p>Centralisez votre activité, automatisez vos suivis et prenez de meilleures décisions avec Intelligence Immobilier.</p><div><Link href="/register" className="ii-button light" data-analytics="final_cta" data-analytics-label="register">Commencer gratuitement <ArrowRight size={16}/></Link><Link href="/demo" className="ii-button ghost" data-analytics="final_cta" data-analytics-label="demo">Explorer la démo</Link></div></section>

    <footer className="ii-footer ii-footer-complete"><div className="ii-footer-brand"><BrandLogo variant="wordmark"/><p>{BRAND_SIGNATURE}</p></div><div className="ii-footer-links"><nav><b>Produit</b><a href="#produit">Fonctionnalités</a><a href="#intelligence">Intelligence AI</a><a href="#tarifs">Tarifs</a><a href="#securite">Sécurité</a></nav><nav><b>Solutions</b><a href="#solutions">Agences</a><a href="#solutions">Gestionnaires</a><a href="#solutions">Propriétaires</a><a href="#solutions">Promoteurs</a></nav><nav><b>Compte</b><Link href="/login">Connexion</Link><Link href="/register">Créer un compte</Link><Link href="/demo">Démo</Link></nav><nav><b>Ressources</b><a href="#faq">FAQ</a><a href="mailto:contact@intelligenceimmobilier.com">Contact</a><a href="mailto:contact@intelligenceimmobilier.com">Programme pilote</a></nav><nav><b>Légal</b><Link href="/confidentialite">Confidentialité</Link><Link href="/conditions">Conditions</Link><Link href="/mentions-legales">Mentions légales</Link></nav></div><div className="ii-footer-legal"><p>© 2026 {BRAND_NAME}. Tous droits réservés.</p><p><span>NINEA : {COMPANY_NINEA}</span><span>RCCM : {COMPANY_RCCM}</span></p></div></footer>
  </main>;
}
