import type { VetUser, Animal, RendezVous, Alerte, DossierMedical } from './types';

// ── Utilisateurs Demo ────────────────────────────────────────────────────────

export const DEMO_USERS: VetUser[] = [
  {
    id: 'vet-001',
    nom: 'Dr. Amadou Diallo',
    email: 'amadou.diallo@vetalert.sn',
    telephone: '+221 77 123 45 67',
    role: 'VETERINAIRE',
    specialite: 'Bovins & Petits Ruminants',
    numeroOrdre: 'ONVS-2021-0456',
    localisation: 'Thiès, Sénégal',
    premium: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'elev-001',
    nom: 'Mamadou Ndiaye',
    email: 'mamadou.ndiaye@ferme.sn',
    telephone: '+221 76 987 65 43',
    role: 'ELEVEUR',
    ferme: 'Ferme Ndiaye — Kaolack',
    localisation: 'Kaolack, Sénégal',
    premium: false,
    createdAt: '2024-02-10',
  },
];

// ── Animaux Demo ─────────────────────────────────────────────────────────────

export const DEMO_ANIMAUX: Animal[] = [
  {
    id: 'anim-001',
    numeroId: 'SN-KAO-2022-0001',
    nom: 'Boubou',
    espece: 'boeuf',
    race: 'Gobra',
    sexe: 'male',
    ageAns: 3,
    ageMois: 2,
    poids: 320,
    etatSante: 'bonne_sante',
    dateNaissance: '2022-03-15',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    notes: 'Animal en bonne forme, bien nourri.',
    createdAt: '2022-04-01',
  },
  {
    id: 'anim-002',
    numeroId: 'SN-KAO-2021-0042',
    nom: 'Fatou',
    espece: 'mouton',
    race: 'Peul-Peul',
    sexe: 'femelle',
    ageAns: 2,
    ageMois: 8,
    poids: 45,
    etatSante: 'en_traitement',
    dateNaissance: '2021-09-20',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    notes: 'Traitement antibiotique en cours. Réévaluation dans 7 jours.',
    createdAt: '2022-01-05',
  },
  {
    id: 'anim-003',
    numeroId: 'SN-KAO-2023-0105',
    nom: 'Sultan',
    espece: 'cheval',
    race: 'Barbe',
    sexe: 'male',
    ageAns: 5,
    ageMois: 0,
    poids: 420,
    etatSante: 'surveillance',
    dateNaissance: '2019-06-10',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    notes: 'Légère boiterie observée, surveillance de la ferrure.',
    createdAt: '2023-07-01',
  },
  {
    id: 'anim-004',
    numeroId: 'SN-KAO-2022-0088',
    nom: 'Bella',
    espece: 'chevre',
    race: 'Saanen',
    sexe: 'femelle',
    ageAns: 1,
    ageMois: 11,
    poids: 28,
    etatSante: 'malade',
    dateNaissance: '2023-07-05',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    notes: 'Fièvre élevée, appétit réduit. Analyses en cours.',
    createdAt: '2023-08-01',
  },
  {
    id: 'anim-005',
    numeroId: 'SN-KAO-2020-0012',
    nom: 'Serigne',
    espece: 'boeuf',
    race: 'Ndama',
    sexe: 'male',
    ageAns: 6,
    ageMois: 3,
    poids: 380,
    etatSante: 'bonne_sante',
    dateNaissance: '2018-02-28',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    createdAt: '2020-03-15',
  },
  {
    id: 'anim-006',
    numeroId: 'SN-KAO-2023-0201',
    nom: 'Aicha',
    espece: 'mouton',
    race: 'Ouled Djellal',
    sexe: 'femelle',
    ageAns: 1,
    ageMois: 4,
    poids: 38,
    etatSante: 'bonne_sante',
    dateNaissance: '2023-01-20',
    proprietaireId: 'elev-001',
    proprietaireNom: 'Mamadou Ndiaye',
    veterinaire: 'Dr. Amadou Diallo',
    createdAt: '2023-02-01',
  },
];

// ── Rendez-vous Demo ──────────────────────────────────────────────────────────

export const DEMO_RDV: RendezVous[] = [
  {
    id: 'rdv-001',
    animalId: 'anim-001',
    animalNom: 'Boubou',
    animalEspece: 'boeuf',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-05-26',
    heure: '09:00',
    type: 'vaccination',
    motif: 'Rappel vaccin FMD + Pasteurellose',
    statut: 'confirme',
    lieu: 'Ferme Ndiaye — Kaolack',
  },
  {
    id: 'rdv-002',
    animalId: 'anim-002',
    animalNom: 'Fatou',
    animalEspece: 'mouton',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-05-25',
    heure: '14:30',
    type: 'traitement',
    motif: 'Contrôle traitement antibiotique',
    statut: 'urgent',
    lieu: 'Clinique Vétérinaire Thiès',
  },
  {
    id: 'rdv-003',
    animalId: 'anim-004',
    animalNom: 'Bella',
    animalEspece: 'chevre',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-05-25',
    heure: '11:00',
    type: 'consultation',
    motif: 'Examen fièvre et résultats analyses',
    statut: 'urgent',
    lieu: 'Ferme Ndiaye — Kaolack',
    notes: 'Résultats des analyses à apporter',
  },
  {
    id: 'rdv-004',
    animalId: 'anim-003',
    animalNom: 'Sultan',
    animalEspece: 'cheval',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-05-28',
    heure: '10:00',
    type: 'controle_sanitaire',
    motif: 'Suivi boiterie + bilan général',
    statut: 'programme',
    lieu: 'Ferme Ndiaye — Kaolack',
  },
  {
    id: 'rdv-005',
    animalId: 'anim-005',
    animalNom: 'Serigne',
    animalEspece: 'boeuf',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-06-02',
    heure: '08:30',
    type: 'vermifuge',
    motif: 'Traitement antiparasitaire trimestriel',
    statut: 'programme',
    lieu: 'Ferme Ndiaye — Kaolack',
  },
  {
    id: 'rdv-006',
    animalId: 'anim-006',
    animalNom: 'Aicha',
    animalEspece: 'mouton',
    veterinaire: 'Dr. Amadou Diallo',
    eleveur: 'Mamadou Ndiaye',
    date: '2026-06-05',
    heure: '15:00',
    type: 'insemination',
    motif: 'Insémination artificielle',
    statut: 'programme',
    lieu: 'Ferme Ndiaye — Kaolack',
  },
];

// ── Alertes Demo ──────────────────────────────────────────────────────────────

export const DEMO_ALERTES: Alerte[] = [
  {
    id: 'alert-001',
    type: 'urgence',
    titre: '🚨 Urgence — Bella en état critique',
    message: 'Bella (chèvre) présente une fièvre à 41.5°C. Intervention immédiate recommandée.',
    animalId: 'anim-004',
    animalNom: 'Bella',
    date: '2026-05-25T08:15:00',
    lue: false,
    priorite: 'urgente',
  },
  {
    id: 'alert-002',
    type: 'rendez_vous',
    titre: 'Rappel RDV — Fatou aujourd\'hui à 14h30',
    message: 'Contrôle traitement antibiotique de Fatou prévu à 14h30 à la Clinique Vétérinaire.',
    animalId: 'anim-002',
    animalNom: 'Fatou',
    date: '2026-05-25T07:00:00',
    lue: false,
    priorite: 'haute',
  },
  {
    id: 'alert-003',
    type: 'vaccin',
    titre: 'Rappel vaccination — Boubou demain',
    message: 'Le vaccin FMD + Pasteurellose de Boubou est programmé demain à 09h00.',
    animalId: 'anim-001',
    animalNom: 'Boubou',
    date: '2026-05-25T06:00:00',
    lue: true,
    priorite: 'haute',
  },
  {
    id: 'alert-004',
    type: 'traitement',
    titre: 'Traitement en cours — Fatou J+3',
    message: 'Fatou est au 3ème jour de son traitement antibiotique. Administrer la dose quotidienne.',
    animalId: 'anim-002',
    animalNom: 'Fatou',
    date: '2026-05-24T18:00:00',
    lue: true,
    priorite: 'normale',
  },
  {
    id: 'alert-005',
    type: 'controle',
    titre: 'Contrôle sanitaire — Sultan dans 3 jours',
    message: 'Le contrôle sanitaire de Sultan est prévu le 28 mai. Penser à préparer la ferrure.',
    animalId: 'anim-003',
    animalNom: 'Sultan',
    date: '2026-05-24T12:00:00',
    lue: true,
    priorite: 'normale',
  },
  {
    id: 'alert-006',
    type: 'rappel',
    titre: 'Vermifuge — Serigne dans 8 jours',
    message: 'Le traitement antiparasitaire trimestriel de Serigne est prévu le 2 juin.',
    animalId: 'anim-005',
    animalNom: 'Serigne',
    date: '2026-05-23T09:00:00',
    lue: true,
    priorite: 'normale',
  },
];

// ── Dossiers Médicaux Demo ────────────────────────────────────────────────────

export const DEMO_DOSSIERS: DossierMedical[] = [
  {
    id: 'dos-001',
    animalId: 'anim-002',
    animalNom: 'Fatou',
    animalEspece: 'mouton',
    type: 'traitement',
    titre: 'Traitement antibiotique — Infection respiratoire',
    description: 'Fatou présentait une toux persistante, sécrétions nasales et fièvre légère (39.8°C). Diagnostic : bronchopneumonie légère.',
    medicaments: ['Oxytétracycline 20%', 'Anti-inflammatoire (Flunixine)'],
    dose: 'Oxytétracycline : 1ml/10kg pendant 5 jours',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-05-22',
    prochainControle: '2026-05-29',
  },
  {
    id: 'dos-002',
    animalId: 'anim-001',
    animalNom: 'Boubou',
    animalEspece: 'boeuf',
    type: 'vaccin',
    titre: 'Vaccination FMD (Fièvre Aphteuse)',
    description: 'Vaccination annuelle contre la fièvre aphteuse. Animal en bonne santé, aucune réaction post-vaccinale observée.',
    medicaments: ['Vaccin FMD polyvalent'],
    dose: '2ml en injection sous-cutanée',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-02-10',
    prochainControle: '2026-05-26',
  },
  {
    id: 'dos-003',
    animalId: 'anim-003',
    animalNom: 'Sultan',
    animalEspece: 'cheval',
    type: 'analyse',
    titre: 'Analyse radiologique membre antérieur droit',
    description: 'Radiographie du boulet droit suite à une boiterie observée. Résultat : légère arthrose débutante. Surveillance recommandée.',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-04-15',
    prochainControle: '2026-05-28',
  },
  {
    id: 'dos-004',
    animalId: 'anim-004',
    animalNom: 'Bella',
    animalEspece: 'chevre',
    type: 'maladie',
    titre: 'Hyperthermie sévère — Cause en investigation',
    description: 'Bella présente une fièvre à 41.5°C, anorexie et abattement général. Prélèvements réalisés pour analyses bactériologiques et virologiques.',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-05-25',
    prochainControle: '2026-05-27',
  },
  {
    id: 'dos-005',
    animalId: 'anim-005',
    animalNom: 'Serigne',
    animalEspece: 'boeuf',
    type: 'vaccin',
    titre: 'Vaccination Pasteurellose',
    description: 'Rappel vaccin Pasteurellose bovine. Animal en excellente condition corporelle.',
    medicaments: ['Pastovax Bovins'],
    dose: '2ml sous-cutané',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-02-15',
  },
  {
    id: 'dos-006',
    animalId: 'anim-001',
    animalNom: 'Boubou',
    animalEspece: 'boeuf',
    type: 'prescription',
    titre: 'Prescription vermifuge — Ivermectine',
    description: 'Traitement antiparasitaire préventif. Charge parasitaire élevée détectée lors de la coproscopie.',
    medicaments: ['Ivermectine 1%'],
    dose: '1ml/50kg en injection sous-cutanée',
    veterinaire: 'Dr. Amadou Diallo',
    date: '2026-03-01',
    prochainControle: '2026-06-01',
  },
];

// ── Constantes UI ────────────────────────────────────────────────────────────

export const ESPECE_LABELS: Record<string, string> = {
  boeuf: '🐄 Bœuf',
  mouton: '🐑 Mouton',
  chevre: '🐐 Chèvre',
  cheval: '🐎 Cheval',
  ane: '🫏 Âne',
  chameau: '🐫 Chameau',
  poule: '🐔 Poule',
  porc: '🐖 Porc',
};

export const TYPE_RDV_LABELS: Record<string, { label: string; color: string }> = {
  vaccination: { label: 'Vaccination', color: '#0a6342' },
  vermifuge: { label: 'Vermifuge', color: '#6d28d9' },
  consultation: { label: 'Consultation', color: '#1d4ed8' },
  insemination: { label: 'Insémination', color: '#db2777' },
  controle_sanitaire: { label: 'Contrôle sanitaire', color: '#b45309' },
  traitement: { label: 'Traitement', color: '#dc2626' },
};

export const ETAT_SANTE_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  bonne_sante: { label: 'Bonne santé', color: '#0a6342', bg: '#d9f2e3' },
  surveillance: { label: 'Surveillance', color: '#b45309', bg: '#fef3c7' },
  en_traitement: { label: 'En traitement', color: '#1d4ed8', bg: '#dbeafe' },
  malade: { label: 'Malade', color: '#dc2626', bg: '#fee2e2' },
  critique: { label: 'Critique', color: '#7f1d1d', bg: '#fca5a5' },
};

export const STATUT_RDV_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  programme: { label: 'Programmé', color: '#1d4ed8', bg: '#dbeafe' },
  confirme: { label: 'Confirmé', color: '#0a6342', bg: '#d9f2e3' },
  termine: { label: 'Terminé', color: '#4b5563', bg: '#f3f4f6' },
  annule: { label: 'Annulé', color: '#9ca3af', bg: '#f9fafb' },
  urgent: { label: '🚨 Urgent', color: '#dc2626', bg: '#fee2e2' },
};
