'use client';
import {useEffect,useState} from 'react';
import {Search,ArrowUpRight,CalendarDays,MapPin,ArrowLeft,Play,ShieldCheck} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Item={id:string,kind:string,data:Record<string,any>};
const categories=['À la une','National','Régions','Diaspora','Touba','Communiqués','Agenda','Photos & vidéos'];
const formatDate=(s:string)=>new Date(s+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});
export default function News({articleId}:{articleId?:string}){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState('À la une'),[query,setQuery]=useState('');
 async function refresh(){setLoading(true);setError('');try{const response=await fetch('/api/public');const body=await response.json();if(!response.ok)throw Error(body.error);setItems(body.records);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 const articles=items.filter(i=>i.kind==='articles'||(i.kind==='activities'&&i.data.type==='Communiqué')).map(i=>i.kind==='activities'?{...i,data:{...i.data,category:'Communiqués',author:'',summary:'',image:'',video:''}}:i).sort((a,b)=>b.data.date.localeCompare(a.data.date));
 const selection=articles.filter(a=>(category==='À la une'||(category==='Photos & vidéos'?(a.data.image||a.data.video):a.data.category===category))&&[a.data.name,a.data.summary,a.data.description,a.data.place].join(' ').toLowerCase().includes(query.toLowerCase()));
 const featured=selection.find(a=>a.data.featured)||selection[0];
 const article=articles.find(a=>a.id===articleId);
 const agenda=items.filter(i=>i.kind==='activities'&&i.data.type!=='Communiqué').sort((a,b)=>a.data.date.localeCompare(b.data.date));
 function photo(a:Item){return a.data.image?<img src={a.data.image} alt={a.data.name} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;}}/>:null;}
 function story(a:Item,lead=false){return <article key={a.id} className={lead?'news-lead':'news-story'}><a href={'/articles/'+a.id}>{photo(a)}<div className="story-copy"><span className="news-category">{a.data.category}{a.data.place?' · '+a.data.place:''}</span><h2>{a.data.name}</h2>{a.data.summary&&<p>{a.data.summary}</p>}<small>{formatDate(a.data.date)}{a.data.author?' · '+a.data.author:''}</small><span className="read-story">Lire l’article <ArrowUpRight size={16}/></span></div></a></article>;}
 return <div className="news-site"><div className="news-strip"><span>LES PATRIOTES RÉPUBLICAINS</span><span>SÉNÉGAL & DIASPORA</span></div><header className="news-masthead"><a href="/" className="news-brand"><img src="/kiiraay-logo.jpeg" alt="Logo Kiiraay"/><div><strong>KIIRAAY <span>INFOS</span></strong><small>L’actualité du parti, au Sénégal et dans la diaspora.</small></div></a><a className="news-admin" href="/gestion"><ShieldCheck size={16}/> Espace de gestion <ArrowUpRight size={16}/></a></header>
 <main className="news-main">{articleId?<><a className="back-link" href="/"><ArrowLeft size={17}/> Toutes les actualités</a>{loading?<p role="status">Chargement de l’article…</p>:error?<div className="error" role="alert">{error}<button onClick={refresh}>Réessayer</button></div>:article?<article className="news-detail"><span className="news-category">{article.data.category}{article.data.place?' · '+article.data.place:''}</span><h1>{article.data.name}</h1><p className="article-meta">{formatDate(article.data.date)}{article.data.author?' · '+article.data.author:''}</p>{article.data.summary&&<p className="article-summary">{article.data.summary}</p>}{photo(article)}<div className="article-body">{article.data.description}</div>{article.data.video&&<a className="primary" href={article.data.video} target="_blank" rel="noopener noreferrer"><Play size={18}/> Voir la vidéo</a>}</article>:<div className="news-empty"><h1>Article indisponible</h1><p>Cet article n’existe pas ou n’est plus publié.</p></div>}</>:<Tabs value={category} onValueChange={setCategory}><TabsList className="news-nav" variant="line">{categories.map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList><div className="news-section-heading"><div><span className="news-kicker">KIIRAAY INFOS</span><h1>{category==='À la une'?'L’actualité du parti':category}</h1></div><label className="search news-search"><Search size={18}/><input aria-label="Rechercher une actualité" placeholder="Rechercher une actualité…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <TabsContent value={category}>{loading?<p role="status">Chargement des actualités…</p>:error?<div className="error" role="alert">{error}<button onClick={refresh}>Réessayer</button></div>:category==='Agenda'?<div className="news-agenda">{agenda.filter(a=>(a.data.name+' '+a.data.place).toLowerCase().includes(query.toLowerCase())).map(a=><article className="agenda-item" key={a.id}><CalendarDays/><div><span className="news-category">{a.data.type} · {formatDate(a.data.date)}</span><h2>{a.data.name}</h2><p><MapPin size={14}/>{a.data.place}</p><p className="agenda-description">{a.data.description}</p></div></article>)}{!agenda.length&&<div className="news-empty"><CalendarDays/><h2>Aucun événement publié</h2><p>Les prochaines réunions, visites et activités du parti seront annoncées ici.</p></div>}</div>:selection.length?<><div className="news-feature-grid">{featured&&story(featured,true)}<aside className="news-sidebar"><span className="news-kicker">LES RUBRIQUES</span><h2>Partout où le parti est présent.</h2>{['National','Régions','Diaspora','Touba'].map(c=><button key={c} onClick={()=>setCategory(c)}>{c}<ArrowUpRight size={17}/></button>)}<p>Actualités, déclarations et rendez-vous de Kiiraay.</p></aside></div><div className="news-grid">{selection.filter(a=>a.id!==featured?.id).map(a=>story(a))}</div></>:<div className="news-feature-grid"><div className="news-empty"><span className="news-category">{category}</span><h2>{query?'Aucun article ne correspond à votre recherche.':'Les prochaines publications apparaîtront ici.'}</h2><p>{query?'Essayez un autre mot-clé.':'Les articles seront présentés dès leur publication par la rédaction.'}</p><a className="primary" href="/gestion">Ouvrir la rédaction <ArrowUpRight size={17}/></a></div><aside className="news-logo-panel"><img src="/kiiraay-logo.jpeg" alt="Kiiraay — Les Patriotes Républicains"/></aside></div>}</TabsContent></Tabs>}
 <footer className="news-footer"><div><strong>KIIRAAY INFOS</strong><p>Actualités nationales · Régions · Diaspora · Touba</p></div><span><ShieldCheck size={14}/> Actualités de Kiiraay</span></footer></main></div>;
}
